### ISSUE TITLE
How to train this network?

### ISSUE THREAD

**Issue by xnowbzhao** [Jia1018/ResGEM-Multi-scale-Graph-Embedding-Network-for-Residual-Mesh-Denoising#1]
I read your paper with great interest and was very impressed by the results you achieved. I would like to compare my own results with yours, and I would be grateful if you could provide some information about your training process. If you are not able to share your code, I would also be grateful if you could provide your experimental results of the synthetic, kinect V1 and V2 dataset. This would allow me to compare my results with yours in a more meaningful way. Thank you!

**Comment by Jia1018** [comment]
Thank you very much for your interest in our work. I'm delighted to hear that you found our results impressive and that you would like to compare them with your own.
We have made our experimental results on the synthetic, Kinect V1, and V2 datasets publicly available. You can access them through the following link: https://drive.google.com/drive/folders/1cV3offz01vJhnpo8ECGSK-OYQKzT3OXJ?usp=drive_link.
I hope this information proves helpful in your research, and please feel free to reach out if you have any further questions or require additional assistance.

**Comment by xnowbzhao** [comment]
Thank you! I have downloaded your denoised meshes, and your results are excellent. However, I have a problem about the Kinect V1, and V2 results, it seems that the face number or vertex number is different to the meshes released by CNR, which prevents the objective comparison, how to solve this problem?

**Comment by Jia1018** [comment]
I checked that the face numbers of the meshes are consistent despite the presence of some redundant vertices. Using the Python package Open3D to read the meshes should help address this issue.

**Comment by xnowbzhao** [comment]
Thank you for you reply!
